version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      #KAFKA_JMX_PORT: 39999
    ports:
      - 22181:2181
      
  
  kafka:
    build: .
    #image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 7071:7071

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=7071:/opt/prometheus/prom-jmx-agent-config.yml
      
      #KAFKA_JMX_PORT: 7071
      #KAFKA_JMX_HOSTNAME: kafka
  


  prometheus:
    image: prom/prometheus
    ports:
      - 9099:9090/tcp
    user: root
    volumes:
      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"


  grafana:
   image: grafana/grafana
   ports:
     - "3000:3000"
   volumes:
     - ./grafana:/var/lib/grafana
