global:
  scrape_interval: 10s 

scrape_configs:
- job_name: kafka
  static_configs:
          - targets: ['kafka:7071']

- job_name: xinfra
  static_configs:
          - targets: ['host.docker.internal:666']